<a href="https://colab.research.google.com/github/WJuniorF/Entregas_POO/blob/main/Taller_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
#Taller_1_Repaso

#1. Crear un programa que pida al usuario ingresar su nombre y edad y los imprima en pantalla.

nombre=str(input("Ingrese su nombre:" ))
edad=int(input("Ingrese su edad:" ))

print(f'Su nombre es {nombre} y tiene {edad} años')

Ingrese su nombre:Walter
Ingrese su edad:30
Su nombre es Walter y tiene 30 años


In [16]:
#2. Escribir una función que calcule el área de un círculo dado su radio.

def a_circulo(r):
  pi=3.1416
  area=round(pi*r**2,2)

  return  f"El area del circulo es {area} unidades cuadradas"

a_circulo(4)

'El area del circulo es 50.27 unidades cuadradas'

In [17]:
#3. Crear un programa que genere una lista de números aleatorios y los imprima en pantalla.
import random

a=random.randrange(0,100,1)
print (f"Este es un número aleatorio:", a)



Este es un número aleatorio: 60


In [18]:
#4. Escribir un programa que determine si un número dado es par o impar.

num=int(input("Ingrese un número: " ))

if num%2==0:
  print(f"El número {num} es par")
else:
  print(f"El número {num} es impar")



Ingrese un número: 7
El número 7 es impar


In [19]:
#5. Crear una función que convierta grados Fahrenheit a grados Celsius.

def convert_temp (f:float):
  a=round((f-32)*5/9,1)
  return (f"{f} grados Fahrenheit equivalen a {a} grados Celsius")



In [20]:
convert_temp(45)

'45 grados Fahrenheit equivalen a 7.2 grados Celsius'

In [21]:
#6. Crear un programa que calcule la suma de los números en una lista dada.

lista=[1,2,3,4,5]

acumulador=0

for i in lista:
  acumulador+=i

print(acumulador)

15


In [22]:
#7. Escribir un programa que encuentre el número más grande y el más pequeño en una lista dada.

print (f"El numero más pequeño de la lista es {min(lista)} y el número mas grande es {max(lista)}")

El numero más pequeño de la lista es 1 y el número mas grande es 5


In [23]:
#8. Crear una función que invierta el orden de los elementos en una lista dada.
def invertir(p:list):
  a=[]
  for i in reversed(p):
    a+=[i]
  print(f"La lista invertida es {a}")
  return


In [24]:
invertir(lista)

La lista invertida es [5, 4, 3, 2, 1]


In [25]:
#9. Crear un programa que genere una matriz de números y la imprima en pantalla.

import numpy as np


In [26]:
rng = np.random.default_rng()
b=rng.integers(10, size=(5,5))
print(b)


[[8 3 4 1 2]
 [3 6 9 7 4]
 [1 4 7 3 3]
 [9 1 2 1 0]
 [5 4 5 9 5]]


In [27]:
#10. Escribir una función que calcule el factorial de un número dado.





In [28]:
#11. Crear un programa que genere una lista de números pares entre 1 y 100.
par_lista=[]

for i in range(1,101):
  if i%2==0:
    par_lista+=[i]

In [29]:
print(par_lista)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [30]:
#12. Crear un programa que imprima los números del 1 al 10 utilizando un ciclo for.

for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [31]:
#13. Crear un programa que pida al usuario ingresar dos números y calcule su suma, resta, multiplicación y división.

def operaciones ():
  a=int(input("Ingresa un número:" ))
  b=int(input("Ingresa un número:" ))

  suma=a+b
  resta=a-b
  multi=a*b
  div=round((a/b),2)
  return print(f"La suma de {a} y {b} es igual a {suma}\nLa resta de {a} y {b} es igual a {resta}\nLa multiplicación de {a} y {b} es igual a {multi}\nLa división de {a} y {b} es igual a {div}")


In [32]:
operaciones()

Ingresa un número:9
Ingresa un número:6
La suma de 9 y 6 es igual a 15
La resta de 9 y 6 es igual a 3
La multiplicación de 9 y 6 es igual a 54
La división de 9 y 6 es igual a 1.5


In [33]:
#14. Escribir una función que calcule la media aritmética de una lista de números.


def media (a:list):
  suma=0

  for i in a:
    suma+=i

  media_a=round((suma/len(a)),2)
  return f"La media aritmética de la lista es {media_a}"

In [34]:

lista_numeros=[5,4,3,2,4,5,7]

media(lista_numeros)

'La media aritmética de la lista es 4.29'

In [35]:

#15. Crear un programa que pida al usuario ingresar una cadena de texto y determine si es un palíndromo o no.

